version: '3.9'

services:
  db:
    image: mariadb
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - football
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MARIADB_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
  adminer:
    image: adminer
    ports:
      - 8181:8080
    networks:
      - football

networks:
  football:
    driver: bridge
